### ISSUE TITLE
Limits of data, the place of whisperX, is there  a place for LLMs?, utterance length

### ISSUE THREAD

**Issue by charlesrwest** [domesticatedviking/TextyMcSpeechy#8]
A few questions, if I may:
1. If you want to make your voice as good as possible, is there any limit to where additional data becomes less useful and the problem comes from other parts of the system?  For instance, the Alba piper voice looks like it was trained on 8 hours of audio?  Is more than 8 hours useful?
2. I already built a pipeline for using whisperx to provide subtitles/timestamps for audio (and then clean it up with an LLM).  Do you think it would be possible to used that to automatically make training data from audio (is there a tool that already does this)?
3. I notice that piper has a utility that converts text to phonemes.  I feel like sometime it mispronounces words and I am not sure if it is the voice model messing up or the text to phonemes converter.  Do you think that the text to phonemes contributes significantly to errors in audio conversion or it's just the model?  Is there a way to format text to control how the model will break it down into phonemes or allow more fine tune control over the voice (such as controlling where pauses are)?
4. I notice that Piper seems to some issues at utterance boundaries.  Is it possible to create training data that spans multiple sentences?

More generally, would you be willing to give advice on how to get the absolute best TTS performance if you are willing to sink some effort into it?  Thanks!

**Comment by domesticatedviking** [comment]
> A few questions, if I may:
> 
>     1. If you want to make your voice as good as possible, is there any limit to where additional data becomes less useful and the problem comes from other parts of the system?  For instance, the Alba piper voice looks like it was trained on 8 hours of audio?  Is more than 8 hours useful?

Theoretically you can never have too much data but practically speaking the size of the dataset has a major impact on the amount of time it takes to train a model.  This the main reason why TextyMcSpeechy is designed to finetune existing language models rather than train them from scratch.    You don't need anywhere near 8 hours of samples to make an existing model sound like a target voice.  

>     2. I already built a pipeline for using whisperx to provide subtitles/timestamps for audio (and then clean it up with an LLM).  Do you think it would be possible to used that to automatically make training data from audio (is there a tool that already does this)?

I am aware of one other user who created a dataset using subtitled youtube videos.   I am not aware of any existing tools that can create trainable datasets direct from audio.    Transcription errors would have a very negative impact on pronunciation especially for smaller datasets. I think it could be an efficient strategy if a human were to proofread it before training, however.

>     3. I notice that piper has a utility that converts text to phonemes.  I feel like sometime it mispronounces words and I am not sure if it is the voice model messing up or the text to phonemes converter.  Do you think that the text to phonemes contributes significantly to errors in audio conversion or it's just the model?  Is there a way to format text to control how the model will break it down into phonemes or allow more fine tune control over the voice (such as controlling where pauses are)?

I don't know very much about how espeak-ng is being used by piper.  I have noticed that dataset transcripts that include abbreviations can introduce unwanted pauses even if the tool is smart enough to expand them correctly --- eg.  if the transcript includes "Dr." it will say "Doctor", but it also adds a long pause because it thinks the period now signals the end of the sentence.
I suspect during preprocessing the text transcripts are converted to phonemes and it might be possible to hand-edit the output prior to training for better results.     The placement of pauses will still probably be heavily influenced by the pretrained TTS model, however.

> 
>     4. I notice that Piper seems to some issues at utterance boundaries.  Is it possible to create training data that spans multiple sentences?

Yes, you can have training data that is more than one sentence in length.   My understanding is that it is important for datasets to include a variety of lengths of utterances (ideally following a normal distribution).    I have also noticed that breathing sounds are included in many datasets and while this makes human voices sound more natural  this makes some of my robot voices sound very strange. 

> 
> 
> More generally, would you be willing to give advice on how to get the absolute best TTS performance if you are willing to sink some effort into it? Thanks!

I am by no means an expert in this subject and couldn't hold a candle to the Piper devs.      If the goal is to create a voice that was indiscernible from the original speaker, I think even the best TTS models I have heard fall short due to flat affect and intonation not matching the target speaker.    Speech-to-speech voice changing models (eg RVC models) deliver much more believable results than TTS provided the source audio is an impersonation of the target speaker. 

In general though, with this tool, the best advice I can give for a good TTS clone is to start with a pretrained model that is as close as possible to the characteristics of the target voice, then to have a well recorded and meticulously transcribed dataset.  The voices I am getting out of TextyMcspeechy are immediately recognizable as the target speaker's voice -- but they are also recognizable as synthetic -- less because of sound quality and more because of the vocal behaviour of the model.
